# Generated by Django 4.1 on 2022-08-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('database', models.FileField(upload_to=upload_app.models.user_directory_path_db, verbose_name='База данных')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('sheet_name', models.IntegerField(default=0, verbose_name='Имя листа')),
                ('skip_row', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'База данных',
                'verbose_name_plural': 'Базы данных',
                'ordering': ['published'],
            },
        ),
        migrations.CreateModel(
            name='SliceBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название базы данных')),
                ('json_db', models.JSONField(verbose_name='Данные JSON')),
                ('filter', models.JSONField(default=dict, verbose_name='Фильтр(поле-значение)')),
                ('sorting', models.JSONField(default=dict, verbose_name='Последовательность сортировки')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата')),
                ('db_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upload_app.database', verbose_name='База выбранных данных')),
            ],
            options={
                'verbose_name': 'Slices',
                'verbose_name_plural': 'Slice',
                'ordering': ['published'],
            },
        ),
    ]
